---
title: "About"
---

Chris studies how people experience and respond to moments of difficulty and failure while learning. He uses a variety of methods, including experimental, quasi-experimental designs, and predictive analytics approaches, to understand what behaviors and thoughts are associated with these experiences. He is also interested in reframing how we conceptualized failure at both an individual and institutional level. While failure is necessary for learning, it is often stigmatized in educational settings. Chris is interested in reframing failure as a necessary and productive part of the learning process, and how we can create more supportive environments for students to experience and learn from failure. 

Outside of the lab, Chris enjoys knitting and playing tennis. You can also find him playing around with computer code, listening to podcasts, or devouring a good book.

## Education

**University of Minnesota - Twin Cities**, [Ed Psych](https://edpsych.umn.edu/) \| Minneapolis, MN

Ph.D. Student in Educational Psychology\| 2022 - Present

**University of Minnesota - Twin Cities**, [Cog Sci](http://www.cogsciphd.umn.edu/index.shtml) \| Minneapolis, MN

Ph.D. Student in Cognitive Science\| 2020 - 2022

**University of Minnesota - Twin Cities**, [MBS](https://ccaps.umn.edu/biological-sciences-masters-degree) \| Minneapolis, MN

Master of Biological Sciences in Anatomy Education \| 2016 - 2020

## Lab Affiliations

[Learning Informatics Lab](https://innovation.umn.edu/informatics/) \| Managing Director \| University of Minnesota - Twin Cities

[Affect, Cognition & Computation Lab](https://www.caitlinsmills.com/) \| Graduate Student Researcher \| University of Minnesota - Twin Cities

[Feedback Lab](https://edpsych.umn.edu/research/labs/martin-vanboekel) \| Graduate Student Researcher \| University of Minnesota - Twin Cities

## Curriculum Vitae & Latest Research

[Curriculum Vitae](files/CV%20Steadman.pdf)

[Using LMS Activity to Identify Early Academic Difficulty in First-Year Students](files/GSRD_26.pdf) 

Presented at CEHD Student Research Day, University of Minnesota - Twin Cities, 2026
